### ISSUE TITLE
iOS saves any file as .html

### ISSUE THREAD

**Issue by prodigy2m** [jimmywarting/StreamSaver.js#148] opened 2020-03-27 00:42 UTC
I've tried everything but even all of the samples you guys provide saves any file as test.txt.html even though the file has been transferred. So if you rename the file it works.

**Comment by jimmywarting** [comment] 2020-03-27 10:23
I don't have an iOS device - so hard for me to test it.

There are two ways to download things in streamsaver
- Downloading using iframes + service worker with content-attachment header
- And building a blob all in memory and use `a[download] href[bloburl]` as an fallback

.html is probably added since it's using the first option... since safari have a problem downloading content generated by the service worker (#69) it should fallback to the second option but probably don't do that. (related to #135) 

I wanted to try and make this changes to streamsaver
```diff
- let useBlobFallback = /constructor/i.test(window.HTMLElement) || !!window.safari
+ let useBlobFallback = /constructor/i.test(window.HTMLElement) || !!window.safari || !!window. WebKitPoint
```
...instead of user agent sniffing. but don't know if it would work for all browsers in iOS

**Comment by jimmywarting** [comment] 2020-03-27 10:28
also i don't think it would be as simple as renaming the file. if you look at the file content it may be a total other thing. (webkit switch modes and just download the url as if the service worker wasn't involved and results in a 404 file)

**Comment by prodigy2m** [comment] 2020-03-27 15:56
Jimmy thanks for a the response. I did test it will my friend. So safari desktop works fine now with extension and everything. iOS safari gives that extension problem but the file is correct. We renamed files that were mp4 as well as pngs all worked after renaming. I didn't want to store it in memory cause that won't allow large files and will crash the browser. Any thoughts?

**Comment by jimmywarting** [comment] 2020-03-27 19:09
A tiny bit confused of what you are saying...

Safari desktop works cuz it builds up the file in the memory and then download the file due to this condition being true
```js
let useBlobFallback = /constructor/i.test(window.HTMLElement) || !!window.safari
```

just tested it on my Mac with newest Safari. Service Worker are not involved at all in safari on desktop...

---

iOS may be a different story. I'm not sure if it's using service worker or not anymore.
`/constructor/i.test(window.HTMLElement)`  is a legacy thing that safari have removed.  And I believe `window.safari` is only available on desktop cuz it's where the webkit push notification lives. My guess is that iOS don't have webkit push and `window.safari`? so the condition `useBlobFallback` must be `false`? A simple test to see if it's using web worker could be by pasting this into the url:

```
javascript:alert(/constructor/i.test(window.HTMLElement)||!!window.safari)
```

>  iOS safari gives that extension problem but the file is correct. We renamed files that were mp4 as well as pngs all worked after renaming

that's odd. I thought iOS safari had the same problem as desktop Safari. (that it couldn't download content being generated by service workers) if now that's the case if it's using service worker after all.



> https://bugs.webkit.org/show_bug.cgi?id=182848
> > I'm trying to saving a ReadableStream with Service Worker and
> > Content-Disposition attachment header but it's not working, is this really
> > fixed, patched and released yet?
> 
> This patch is not fully fixing the issue, **it only allows the network process to redo the download by > triggering another network request.
Any service worker generated content will not be downloaded.**

That's the reason why i think it's odd... and that the reason why Safari must use the blob fallback and consume lots of memory until it's finish.

--- 

So to even tackle this and to possible resolve this then i first need to know
1. is it using service worker or if it's using the blob fallback in iOS?
2. if it is using Service Workers then: dose it trigger another network request? i presume not since you are saying you got the right content and you could use the file by just renaming it. So it must have been able to download things generated by a service worker.

(...I'm so confused right now)

I think the reason why `.html` was added was b/c it used the iframe to download the content. hence why it also must have used service worker instead of the blob fallback: `<a download="name.mp4" href="url">`. cuz i'm pretty sure `a[download]` would save the file with the right filename. but i could be wrong too.

I'm sorry I can't help you debug this and fix it. The only think I can do is to help you troubleshoot it and hope that you submit a working PR.

**Comment by workflowmagic** [comment] 2020-04-02 23:55
Hello, I am using streamsaver to save .json files and I am getting the same result on my iphone where the file is saved as   file_name.json.html .

**Comment by jimmywarting** [comment] 2020-04-05 19:55
could you tell me how the file is downloaded?
there is two way it could have been saved - either throught streams or generating a blob and then save

**Comment by begoat** [comment] 2020-04-07 00:38
In my case, I use this lib to download through streams.

In desktop Safari, it works.
while in iOS 10.13
*  it promotes `This site is attempting to open a popup window`, Then i Click allow.
* It navigates me to another page and nav back.
* It promotes `Do you want to download `xxx.exe.html`? I click download.
* After all blob transaction is finished, it download a file called `xxx.exe`

When i open this file, it's size is only 9k and the page is github 404 page
@jimmywarting

**Comment by Evoks** [comment] 2020-04-07 14:24
Hello everyone, 

You should use the BlobFallback for Safari on iOS, I put 
`let useBlobFallback = /constructor/i.test(window.HTMLElement) || window.WebKitPoint`
in the code, and it works like a charm.

The only issue is when the file you want to download is getting too big, the webpage is being refreshed before it finished to download the file. I hope it will be improved in iOS 14. :)

**Comment by Evoks** [comment] 2020-04-07 14:35
And to answer to @jimmywarting , it generates a blob and then save the file.

**Comment by jimmywarting** [comment] 2020-04-07 15:59
closed via dc0c9da

**Closed** 2020-04-07 15:59 UTC

**Comment by jimmywarting** [comment] 2020-04-07 16:08
2.0.4 released

**Comment by jimmywarting** [comment] 2020-04-07 18:02
dc0c9da may have solved the issue for iOS but brought an other issue that it now uses the memory to build blobs.

We could maybe still use the streaming approach but changed the way thing where trigger. perhaps instead of trigger the download with a iframe, maybe we could simply just open the temporary link or changed some headers. but over the years with streamsaver i have come to learn that iframes are better ways to trigger downloads - just can't remember what they where

**Comment by stanimirivanovde** [comment] 2020-11-03 00:37
I still see this issue on my iPhone with latest iOS 14.1. I have a simple HTML page that encrypts a file. Works on desktop Firefox, Chrome and Safari. Doesn't work on iOS. It saves the file as HTML and the console gives me the following error:

<img width="1049" alt="Screen Shot 2020-11-02 at 19 21 20" src="https://user-images.githubusercontent.com/16974967/97933380-816bda00-1d6a-11eb-967b-2f7738845919.png">

<img width="200" src="https://user-images.githubusercontent.com/16974967/97933482-cc85ed00-1d6a-11eb-981b-2aa2038484cb.jpeg">

It still adds the .html file at the end and saves the file as a blank 404 github error page:

<img width="615" alt="Screen Shot 2020-11-02 at 19 26 55" src="https://user-images.githubusercontent.com/16974967/97933661-4ae28f00-1d6b-11eb-8317-00ee927978e3.png">

In order to get my encrypted file to save I had to disable clearing of cookies on browser close for Firefox:

<img width="714" alt="Screen Shot 2020-10-31 at 13 20 14" src="https://user-images.githubusercontent.com/16974967/97933776-9b59ec80-1d6b-11eb-9019-6d710d1eaa94.png">

And had to add my site on the allowed sites in Chrome for storing cookies:

<img width="672" alt="Screen Shot 2020-11-02 at 16 56 47" src="https://user-images.githubusercontent.com/16974967/97933839-c5abaa00-1d6b-11eb-9b41-b4e546ee5dd0.png">

Safari worked well out of the box. But I wonder if something similar needs to be done for iOS. I looked and played with all the cookie settings but nothing worked. I am using a self signed cert which might be another issue. Not sure if the browser is preventing the download from an untrusted source. So I installed my self-signed trust in the iOS trust store but still the same issue. I disabled the content blockers but still the same problem.

Not sure at this point if I'm doing something wrong or Safari on iOS is not working right.

**Comment by jimmywarting** [comment] 2020-11-03 08:50
# the cookie problem 

I happen to know already that cookie settings have some roll in this. But i don't use cookies anywhere and cookies are not required on mine or githubs part.
Service worker can kinda act like a cookie manager by itself even if you are not allowed to store cookies. So that's why browser disabled third party service workers. 

If you host the service worker yourself than you can get away with some problems regarding that
then you need to change the mitm too:
```js
streamSaver.mitm = 'https://example.com/mitm.html'
```

# safari can't use service worker

Safari isn't able to download content generated data from within a service worker due to this bug:
- https://bugs.webkit.org/show_bug.cgi?id=202142 
- <s>https://bugs.webkit.org/show_bug.cgi?id=201580</s> (older, but marked as duplicate of 202142)
- <s>https://bugs.webkit.org/show_bug.cgi?id=182848</s> just partially fixed the issue, hate the way they went to go about it. 

it's blocking #69 and i still haven't figure out a real, good detection script to find out when/if safari can can use service worker or not. it have all the bits and pieces needed to work, readableStream, fetch, service worker... so a feature detection is hard. I Guess i have to do a other feature detection related to the same release + a detection if it's safari or not. (unless i can come up with a real/better test to see if downloads from service worker can be used)

So what I temporarily have done is a detection if it's safari and assemble a Blob in the memory on the main thread and download it using a `<a download>` link instead. This isn't the RAM friendliest solution but at least you are able to save some stuff.

So the fact that you get the 404 github page indicates that it's trying to use the service worker approach instead of using the blob construction fallback cuz this part isn't evaluated as `true` on iOS?
```js
/constructor/i.test(global.HTMLElement) || !!global.safari || !!global.WebKitPoint
```

I don't have a iPhone so i'm not able to test this

**Comment by stanimirivanovde** [comment] 2020-11-03 20:25
Thanks for the explanation. It turned out I wasn't using the latest versions of StreamSaver.js, web-streams-polyfill and node-forge. So I upgraded them to the latest versions. Right now I can successfully save the encrypted/decrypted files on all browsers and devices I've tested on. Here is my repo if you're interested to see what I'm doing: https://github.com/stanimirivanovde/browser-power

Thanks for the great library!

**Comment by jimmywarting** [comment] 2020-11-03 21:35
> Edit: I forgot to mention that the error in the iOS Safari console still persists

What error message?

**Comment by stanimirivanovde** [comment] 2020-11-03 22:44
It's the one from my comment above: [link to screenshot](https://user-images.githubusercontent.com/16974967/97933380-816bda00-1d6a-11eb-967b-2f7738845919.png)

**Comment by jimmywarting** [comment] 2020-11-04 11:24
@stanimirivanovde nothing to worry about i guess. see: https://github.com/jimmywarting/StreamSaver.js/issues/141#issuecomment-583908267

**Comment by stanimirivanovde** [comment] 2020-11-04 13:56
Sounds good, thanks. I tested the code on my iPhone and iPad and it works great. The warning only appears in Safari in iOS though. Not on the desktop Safari.
