### ISSUE TITLE
Example doesn't work in firefox

### ISSUE THREAD

**Issue by biscoe916** [jimmywarting/StreamSaver.js#88] opened 2019-03-13 18:43 UTC
Tried running the example in the latest version of Firefox (65.0.1 (64-bit)), but to no avail.

I get the prompt saying ReadableStreams arent' supported, and I should update it in chrome.

**Comment by biscoe916** [comment] 2019-03-13 19:04
@jimmywarting I noticed a commit from 6 day ago (https://github.com/jimmywarting/StreamSaver.js/commit/ae8dc5aac7cecc31ba29699b6354b91db99b7ebc), where you moved FF support from No, to Yes. What am I doing wrong?

**Comment by jimmywarting** [comment] 2019-03-13 21:01
I have updated the support detection and re-enabled the stream polyfill
the problem is that it supports minium ServiceWorker+ReadableStream but made a check for WritableStream as well, but it can be polyfilled

I'm almost thinking of adding a other method to save a ReadableStream instead of using a WritableStream since all other browsers are so slow at adding WritableStream & TransformStream

**Comment by biscoe916** [comment] 2019-03-14 17:24
@jimmywarting I see, so the support detection needs to be updated? Would you like me to submit a PR?

**Comment by jimmywarting** [comment] 2019-03-14 18:06
I already changed it

**Comment by biscoe916** [comment] 2019-03-28 17:25
The "fetch" example still doesn't work in firefox :(

**Comment by jimmywarting** [comment] 2019-04-12 22:18
If you have been following https://github.com/jimmywarting/StreamSaver.js/pull/92#issuecomment-478649292 you will see a conversation about a mixing problem with native and or polyfilled versions.

it have been solved now.
The recommended way now is to include the ponyfilled version of the stream api instead of overriding the global state.

you can either include the ponyfilled cdn version and it will be taken cared for you 
or you can set it your self

`StreamSaver.WritableStream = require('module').WritableStream`

it has been fixed in #92 and changed in the example.html

the next thing to do is

- [ ] update the readme
- [ ] publish a new npm version
- [ ] tag it
- [ ] update gh-pages (demo)

Living this issue open till all the 4 task are complete

**Comment by VadimZhiltsov** [comment] 2019-05-15 09:20
@jimmywarting I've published it to gh-pages in my fork and it stills seems to be not working with FireFox on my end.

![image](https://user-images.githubusercontent.com/10270666/57764146-90d90c80-770b-11e9-96b7-eb8811fb4e00.png)
You can try it from my fork:
https://vadimzhiltsov.github.io/StreamSaver.js/example.html

Are changes for FF support still required?

**Comment by jimmywarting** [comment] 2019-05-15 19:57
quick update

Had to take a break from StreamSaver and work on other fun web torrenting things.
But I did try to make an effort working with new features and other bug reports on StreamSaver today, but i never got the chance. probably going to be busy tomorrow also 😞

**Comment by jimmywarting** [comment] 2019-05-28 21:41
FYI, I Have refactored quite a bit of code and it's working well in most browser now (even safari with the blob + `a[download]` fallback)

I'm ready to make a release very soon. But i can't just put it up there b/c ppl rely on the current mitm + sw hosted on github pages. So i have to make sure that the old StreamSaver lib is backward compatible when i upload the new mitm + sw to github pages before i can even make a new release.

It's too late now to make the switch now. Have to watch out for any breaking changes. So the plan is

- **Tomorrow:** Test that old streamsaver.js works well and is backward compatible with the new mitm + sw
- **Day after tomorrow:** hopefully make a new release 🙂  

Now when i came to think about it i May also have to update the registered service worker somehow if it's already installed. that will also be a task for tomorrow.

**Closed** 2019-05-31 07:46 UTC
Labels: In Progress
