### ISSUE TITLE
Page becomes unresponsive when writing a new stream from data received over the internet

### ISSUE THREAD

**Issue by ajaydevarakonda** [jimmywarting/StreamSaver.js#162] opened 2020-06-03 05:12 UTC
I have another branch which has a writing file to web sandbox file which does not freeze the ui. But as I cannot download the file from sandbox, I started to use stream saver. 

The ui ends up freezing and ends up with page unresponsive when I try to use stream saver. Following is the stream saver part of the code.

```javascript
// hardcoding values
const filename = 'example.txt';
const filesize = 10000000000; // 10 GB

const fileStream = streamSaver.createWriteStream(filename, {
  size: filesize
});

const write = fileStream.getWriter();

// this function will be called whenever new data arrives.
function onMessage(receivedData) {
  const blob = new Blob(receivedData)
  const readableStream = blob.stream();
  const reader =  readableStream.getReader();
  receievedBlob = await reader.read();
  await writer.write(receivedData.value);
}

function onDone() {
  writer.close();
}
```

I have also created a [stackoverflow question](https://stackoverflow.com/questions/62126157/browser-ui-freezes-and-throws-page-unresponsive-when-using-streamsaver-js-with-l).

**Comment by jimmywarting** [comment] 2020-10-16 22:50
duplicate of https://github.com/jimmywarting/StreamSaver.js/issues/145#issuecomment-598468153

**Closed by jimmywarting** 2020-10-16 22:50 UTC
