### ISSUE TITLE
Network failed!

### ISSUE THREAD

**Issue by hosseinGanjyar** [jimmywarting/StreamSaver.js#45] opened 2017-02-15 23:33 UTC
I using **StreamSaver** and **NodeJS** together for save _10,000,000 Records_ into a file with **.Json** format. After run app and download about many records(200,000 or 300,000 or more), downloading canceled and abort file.json and show error "Network failed" on downloader in browser.
**Notice**: I haven't any error in console and I downloaded about 500MB or more...So no problem in range/memory.
Why? 

## Server.js
```
var http = require('http');
var express = require('express');
var app = express();
var server = http.Server(app);
var io = require('socket.io')(server);

io.on('connection', function (socket) {
    console.log('Connection is ready!')
    socket.on('get_records', function (data) {
    var connection = new sql.Connection(config, function (err) {
        if (err) {
            console.log(err.message);
        }

        var request = new sql.Request(connection);
        request.stream = true;

        request.query("Select * from my_table");
        // ... error checks
        request.on('recordset', function (recordset) {
            // Emitted once for each recordset in a query
        });

        request.on('row', function (record) {
            // Emitted for each row in a recordset
            socket.emit('recieve_records', record); //send record by record to client
        });

        request.on('error', function (err) {
            console.log(err.message);
        });

        request.on('done', function (returnValue) {
            // Always emitted as the last one
        });
    });
});
```

## client.js
```
var fileStream = streamSaver.createWriteStream('filename.json');
writer = fileStream.getWriter();
encoder = new TextEncoder();

socket.on('recieve_records', function (data) {
    var uint8array = encoder.encode(data + "\n"); // data='every things'
    writer.write(uint8array);
});
```

[Image of Error](https://i.stack.imgur.com/Mh0rx.png)

**Comment by jimmywarting** [comment] 2017-02-16 13:32
closing due to duplicate of #39

**Comment by hosseinGanjyar** [comment] 2017-02-18 15:27
@jimmywarting , I don't want retain data into memory(RAM) using **_IndexedDB_**. My data are very large ~2GB.

**Comment by jimmywarting** [comment] 2017-02-18 22:42
This is the same kind of error related to #39 no need to have two issue open that is of the same kind.
There is nothing I can do to fix it. It's a browser limitation unfortunately. 

Reason is that the people that came up with the spec don't want the service worker to live longer then 5 minutes, to avoid bitcoin mining or other abusing code

**Comment by hosseinGanjyar** [comment] 2017-02-20 05:42
@jimmywarting **StreamSaver.js** is very very inefficient : 1- not support firefox , 2- problem with big data

**Comment by jimmywarting** [comment] 2017-02-20 09:26
There is no problem with big data. There's a problem with long living service workers. If you have all that data locally then you can save every thing with no problem.

But I agree. It's somewhat inefficient atm

**Closed by jimmywarting** 2017-02-20 09:26 UTC

**Comment by hosseinGanjyar** [comment] 2017-02-20 11:40
@jimmywarting I don't use service workers.

**Comment by jimmywarting** [comment] 2017-02-20 12:45
With StreamSaver you do... You are actually sending the data to a service worker.

**Comment by maikelf** [comment] 2018-11-30 14:31
I have a similar problem. I have implemented a simple demo in a js file running on the client. This to test before taking it to the real project. I'm doing a csv with 300 columns and adding random rows every 5 seconds. Everything starts well, but the moment comes when I get Filed - Network Error. I do not know if it's really my ignorance. I put the code here to see if they can help me.

`<script src="StreamSaver.js-master/StreamSaver.js"></script>
<script src="https://cdn.rawgit.com/creatorrr/web-streams-polyfill/master/dist/polyfill.min.js"></script>
<body>
</body>
<script>
function getHeader(counts) {
	let header=['timestamp'];
	for(var i=0; i<counts; i++) {
		header.push('var_'+i);
	}
	return header.join() + '\n';
}

function generateCSV(counts) {
	const rows = Math.random(2, 100);
	let row = [];
	let content = [];
	for(var i=0; i<rows; i++) {
		row.push(new Date().toISOString());
		for(var j=0; j<counts; j++) {
			row.push(Math.random());					
		}
		content.push(row.join());
	}
	return content.join('\n');
}


const fileStream = streamSaver.createWriteStream('filename.txt');
const writer = fileStream.getWriter();
const encoder = new TextEncoder;
const varCounts = 300;
let data  = getHeader(varCounts);
let uint8array = encoder.encode(data + "\n\n");
writer.write(uint8array);

var i = 0;
var interval = setInterval(function(){
	let data = generateCSV(varCounts);
	let uint8array = encoder.encode(data + "\n\n");
	writer.write(uint8array);
	i++;
	console.log(i);
	delete data;
	delete uint8array;
	if(i === 100) {
		clearInterval(interval);
		writer.close()
	}
}, 5000);
</script>`

**Comment by jimmywarting** [comment] 2018-11-30 18:45
@maikelf 

Did some math: 100 * 5 sec = 8.3 minutes
what you experiencing is a service worker restart that happens after 5 minutes of running and is related to issue: #39

**Comment by hosseinGanjyar** [comment] 2018-12-01 04:15
@jimmywarting Why did you do and put a sample of solution?
